FORMAT: 1A
HOST: https://localhost

# EasyHealth+

API for using platform EasyHealth+, project of Software Engineering 2022

## Signup [/api/v1/signup]

### Signup a new patient [POST]

Creates a new user which can enter the platform as patient. Then he can perform all the task of a patient.

+ Request (application/json)

    + Attributes
        - email (string, required) - Email of the patient
        - password (string, required) - Password chosen by the patient
        - nome (string, required) - Name of the patient
        - cognome (string, required) - Surname of the patient
        - residenza (string, required) - Address of the patient
        - CF (string, required) - Fiscal Code of the patient
        - CodPA (string, required) - Assurance Plan Code of the patient

+ Response 200

    User created
    
    + Body

            {
                "success": "true"
            }

+ Response 400
    
    Wrong Format. Missing one or more parameters.
    
    + Body
            
            {
                "success": "false",
                "reason": "Wrong format",
                "error": "1"
            }

+ Response 406
    
    User already exists. Error 2 for the CF, error 3 for the email
    
    + Body
            
            {
                "success": "false",
                "reason": "",
                "error": ""
            }

## Verify email [/api/v1/verify_email{?id}]

### Verify email of a created user [GET]

Verify email of a created user by knowing his id.

+ Parameters

    + id - User id
        
+ Response 200
    
    + Headers            
        
                Location: /